#ifndef _RAP_CONFIG_HH_
#define _RAP_CONFIG_HH_

#define ENABLE_BYPASS true
#define RAP_DEAD_COUNTER_SATURATION 3
#define RAP_LEARNING_THRESHOLD 20
#define RAP_WINDOW_SIZE 20
#define RAP_INACURACY_TH 0.72


#endif
